# Minecraft y NeoForge
mcversion=1.21.1
neoversion=21.1.240
minecraft_version_range=[1.21.1,1.22)
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod Info
modid=kubejsindustrialforegoing
modname=kubejsindustrialforegoing
mod_name=KubeJS Industrial Foregoing
author=bobvarioa, NadienDev
mod_version=1.0.0
tag_lanzador=NeoForge
mod_license=All Rights Reserved
mod_description=KubeJS recipe schemas for Industrial Foregoing
issue_tracker=https://github.com/BobVarioa/kjsindustrialforegoing/issues

#Dependencies Versions
kubejs_version=2101.7.2-build.368
kubejs_version_range=[2101.7.0,)
rhino_version=2101.2.8-build.91
if_version=1.21-3.6.39
if_version_range=[1.21,)
titanium_version=1.21-4.0.45
